apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\tasmiya_kadur\demo\kompose.exe convert -f docker-compose.yaml -o manifest/
    kompose.version: 1.24.0 (7c629530)
  creationTimestamp: null
  labels:
    io.kompose.service: datahub-frontend-react
  name: datahub-frontend-react
spec:
  ports:
    - name: "9002"
      port: 9002
      targetPort: 9002
  selector:
    io.kompose.service: datahub-frontend-react
status:
  loadBalancer: {}
