apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\tasmiya_kadur\demo\kompose.exe convert -f docker-compose.yaml -o manifest/
    kompose.version: 1.24.0 (7c629530)
  creationTimestamp: null
  labels:
    io.kompose.service: datahub-gms
  name: datahub-gms
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: datahub-gms
status:
  loadBalancer: {}
