apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    datahub_setup_job: "true"
    kompose.cmd: C:\Users\tasmiya_kadur\demo\kompose.exe convert -f docker-compose.yaml -o manifest/
    kompose.version: 1.24.0 (7c629530)
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch-setup
  name: elasticsearch-setup
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elasticsearch-setup
  strategy: {}
  template:
    metadata:
      annotations:
        datahub_setup_job: "true"
        kompose.cmd: C:\Users\tasmiya_kadur\demo\kompose.exe convert -f docker-compose.yaml -o manifest/
        kompose.version: 1.24.0 (7c629530)
      creationTimestamp: null
      labels:
        io.kompose.network/: "true"
        io.kompose.service: elasticsearch-setup
    spec:
      containers:
        - env:
            - name: ELASTICSEARCH_HOST
              value: elasticsearch
            - name: ELASTICSEARCH_PORT
              value: "9200"
            - name: ELASTICSEARCH_PROTOCOL
              value: http
            - name: ELASTICSEARCH_USE_SSL
              value: "false"
            - name: USE_AWS_ELASTICSEARCH
              value: "false"
          image: linkedin/datahub-elasticsearch-setup:head
          name: elasticsearch-setup
          resources: {}
      hostname: elasticsearch-setup
      restartPolicy: Always
status: {}
