apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\tasmiya_kadur\demo\kompose.exe convert -f docker-compose.yaml -o manifest/
    kompose.version: 1.24.0 (7c629530)
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\tasmiya_kadur\demo\kompose.exe convert -f docker-compose.yaml -o manifest/
        kompose.version: 1.24.0 (7c629530)
      creationTimestamp: null
      labels:
        io.kompose.network/: "true"
        io.kompose.service: elasticsearch
    spec:
      containers:
        - env:
            - name: ES_JAVA_OPTS
              value: -Xms256m -Xmx512m -Dlog4j2.formatMsgNoLookups=true
            - name: OPENSEARCH_JAVA_OPTS
              value: -Xms512m -Xmx512m -Dlog4j2.formatMsgNoLookups=true
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"
          image: elasticsearch:7.10.1
          livenessProbe:
            exec:
              command:
                - curl -sS --fail http://elasticsearch:${DATAHUB_ELASTIC_PORT:-9200}/_cluster/health?wait_for_status=yellow&timeout=0s
            failureThreshold: 3
            periodSeconds: 1
            timeoutSeconds: 5
          name: elasticsearch
          ports:
            - containerPort: 9200
          resources:
            limits:
              memory: "1073741824"
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: esdata
      hostname: elasticsearch
      restartPolicy: Always
      volumes:
        - name: esdata
          persistentVolumeClaim:
            claimName: esdata
status: {}
