apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    datahub_setup_job: "true"
    kompose.cmd: C:\Users\tasmiya_kadur\demo\kompose.exe convert -f docker-compose.yaml -o manifest/
    kompose.version: 1.24.0 (7c629530)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-setup
  name: kafka-setup
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-setup
  strategy: {}
  template:
    metadata:
      annotations:
        datahub_setup_job: "true"
        kompose.cmd: C:\Users\tasmiya_kadur\demo\kompose.exe convert -f docker-compose.yaml -o manifest/
        kompose.version: 1.24.0 (7c629530)
      creationTimestamp: null
      labels:
        io.kompose.network/: "true"
        io.kompose.service: kafka-setup
    spec:
      containers:
        - env:
            - name: DATAHUB_PRECREATE_TOPICS
              value: "false"
            - name: KAFKA_BOOTSTRAP_SERVER
              value: broker:29092
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: USE_CONFLUENT_SCHEMA_REGISTRY
              value: "TRUE"
          image: linkedin/datahub-kafka-setup:head
          name: kafka-setup
          resources: {}
      hostname: kafka-setup
      restartPolicy: Always
status: {}
