apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\Users\tasmiya_kadur\demo\kompose.exe convert -f docker-compose.yaml -o manifest/
    kompose.version: 1.24.0 (7c629530)
  creationTimestamp: null
  labels:
    io.kompose.network/: "true"
    io.kompose.service: mysql
  name: mysql
spec:
  containers:
    - args:
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_bin
        - --default-authentication-plugin=mysql_native_password
      env:
        - name: MYSQL_DATABASE
          value: datahub
        - name: MYSQL_PASSWORD
          value: datahub
        - name: MYSQL_ROOT_PASSWORD
          value: datahub
        - name: MYSQL_USER
          value: datahub
      image: mariadb:10.5.8
      livenessProbe:
        exec:
          command:
            - mysqladmin ping -h mysql -u $MYSQL_USER --password=$MYSQL_PASSWORD
        failureThreshold: 5
        periodSeconds: 1
        timeoutSeconds: 5
      name: mysql
      ports:
        - containerPort: 3306
      resources: {}
      volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d/init.sql
          name: mysql-claim0
        - mountPath: /var/lib/mysql
          name: mysqldata
  hostname: mysql
  restartPolicy: OnFailure
  volumes:
    - name: mysql-claim0
      persistentVolumeClaim:
        claimName: mysql-claim0
    - name: mysqldata
      persistentVolumeClaim:
        claimName: mysqldata
status: {}
