apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\tasmiya_kadur\demo\kompose.exe convert -f docker-compose.yaml -o manifest/
    kompose.version: 1.24.0 (7c629530)
  creationTimestamp: null
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
  selector:
    io.kompose.service: zookeeper
status:
  loadBalancer: {}
